### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Must start Twitter Kit with Fabric.with() first

### ISSUE THREAD

**Issue by shawns582** [chroa/twitter-connect-plugin#10]
First off, thanks for this plugin! I have followed all the installation steps (with Fabric key, Twitter API key and Twitter Secret key), but my app is crashing when I try to do Twitter login().  Below is the stack trace:

Fatal Exception: java.lang.IllegalStateException: Must start Twitter Kit with Fabric.with() first
       at com.twitter.sdk.android.Twitter.checkInitialized(Twitter.java:43)
       at com.twitter.sdk.android.Twitter.logIn(Twitter.java:87)
       at com.manifestwebdesign.twitterconnect.TwitterConnect$1.run(TwitterConnect.java:99)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

I'd appreciate any help as I'm waiting on this to push my app to the stores.  Thanks.

**Comment by billy124** [comment]
Hi did you have any luck with this issue?

**Comment by shawns582** [comment]
@billy124 checkout what I did here:
https://github.com/ManifestWebDesign/twitter-connect-plugin/issues/23#issuecomment-358275036

**Comment by mulikiran** [comment]
same issue  with  me any solution for this ?

**Comment by ciekawy** [comment]
also wondering about any progress, there is also an issue on the FabricPlugin https://github.com/sarriaroman/FabricPlugin/issues/84

**Comment by guylando** [comment]
Newest twitterkit does not use fabric at all, try this version of the plugin:
It has the LATEST twitterkit sdks both for android and ios and fixes the various bugs existing in the other versions of this plugin. Also added info about some gotchas and important things to pay attention to in the readme. Enjoy: https://github.com/guylando/twitterkit3-plugin
Tested and works in latest ios and android
